apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "kubenews"
        - name: POSTGRES_USER
          value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432

